const refs = {
  productsList: document.querySelector('.products-list'),
  logoLink: document.querySelector('.logo-link'),
  searchBtn: document.querySelector('.bi-search'),
  searchForm: document.querySelector('.search-form'),
  loginCloseModalBtn: document.querySelector('.js-loginBtnClose'),
  loginModalBackdrop: document.querySelector('.js-loginBackdrop'),
  loginSignIn: document.querySelector('.js-SignIn'),
  registerCloseModalBtn: document.querySelector('.js-registerBtnClose'),
  registerModalBackdrop: document.querySelector('.js-registerBackdrop'),
  registerSignUp: document.querySelector('.js-SignUp'),
  menuContainer: document.querySelector('.menu-list-container'),
  userBar: document.querySelector('.menu-user-link'),
  closeModalBtn: document.querySelector('.movieModalClose'),
  modalBackdrop: document.querySelector('.js-movieModal'),
  modalContainer: document.querySelector('.movieModal'),
  allMovieList: document.querySelector('.products-list'),
  movieWrap: document.querySelector('.movieModalWrap'),
  spinner: document.querySelector('#spinner'),
  teamModal: document.querySelector('.team_list'),
  teamModalBtnOpen: document.querySelector('.team__modal'),
  teamModalBtnClose:document.querySelector('.teamModalBtnClose'),
  teamModalBackdrop: document.querySelector('.teamModalBack'),
};

export default refs;
