import './scss/base.scss';
import './js/refs';
import './js/pagination';
import './js/movieModal';
import './js/menu';
// import './js/render_main_page_from_logo';
import './js/replace_empty_pic';
import './js/loginModal';
import './js/registerModal';
import './js/search_film';
import './js/topFilms';
import './js/wrong_input';
import './js/team_Modal';
import './js/fb/main_fb';
